server:
  port: ${PORT:8081}
ff4j:
  api:
    context-path: /api/v1/ff4j     # default '/api/ff4j'
    spring-doc:
      enabled: true                # default 'false'
  audit:
    enabled: true                  # default 'false'
springdoc:
  swagger-ui:
    tags-sorter: "alpha"
    operations-sorter: "alpha"
  group-configs:
    - group: "root"
      pathsToMatch: "/**"
      packagesToScan: "org.ff4j.spring.boot.starter.webflux.sample.rest"